#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/
set -x

echo "[***] Build hook starting..."

# $(echo "index.docker.io/user/respository" | cut -d '/' -f 3) = "repository"
APPLICATION=$(echo "${DOCKER_REPO}" | cut -d '/' -f 3)

echo "[---] CURRENT WORKING DIRECTORY: $(pwd)"
echo "[---] DOCKERFILE_PATH: ${DOCKERFILE_PATH}"
echo "[---] DOCKER_REPO: ${DOCKER_REPO}"
echo "[---] IMAGE_NAME: ${IMAGE_NAME}"
echo "[---] APPLICATION: ${APPLICATION}"


export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
echo "Using BUILD_INFO=${BUILD_INFO}"
docker buildx build \
	--platform linux/amd64,linux/arm/v7 \
    --progress plain \
    --push \
    -t ci4rail/robot:${SOURCE_BRANCH} .
