#!/bin/bash

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
docker run --rm --privileged multiarch/qemu-user-static:register --reset

docker buildx create \
	--name builder \
	--driver docker-container \
	--platform linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6 \
	--use
docker buildx inspect --bootstrap