#!/bin/bash

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
docker run --rm --privileged multiarch/qemu-user-static:register --reset -p yes

docker buildx create \
	--name builder \
	--driver docker-container \
	--platform linux/arm/v7 \
	--use
docker buildx inspect --bootstrap